### ISSUE TITLE
SSG

### ISSUE THREAD

**Issue by BoggerByte** [BoggerByte/rogalik-landing#6]
Commercial website should have a good SEO so it is necessarry to setup static site generation

## TODO
- [x] Optimize build time by migrating to bun
- [x] Migrate to sveltekit
- [x] Configure linter
- [x] Configue formatter
- [x] Set up SSG
